title: Conferences Samples
description: Code samples from my conferences
google_analytics: UA-33705301-1
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

# Google Analytics
google_analytics: UA-33705301-1